apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartKind: pages
    chartRepository: https://github.com/jenkins-x-bdd/repo.git
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
    owner: jelockro
    repository: jx3-kind
  - key: staging
  ingress:
    domain: 172.25.86.242.nip.io
    ignoreLoadBalancer: true
    kind: ingress
    namespaceSubDomain: .jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: jelockro
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
