# Source: metallb/templates/config-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
  labels:
    app.kubernetes.io/component: metallb
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: metallb
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'metallb'
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - "172.25.86.242-172.25.86.242"
