# Source: metallb/templates/config-watcher-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: metallb
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: config-watcher
  namespace: metallb-system
  annotations:
    meta.helm.sh/release-name: 'metallb'
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
