# Source: metallb/templates/controller-rb.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: metallb
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: controller
  namespace: metallb-system
  annotations:
    meta.helm.sh/release-name: 'metallb'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: controller
subjects:
  - kind: ServiceAccount
    name: controller
