# Source: metallb/templates/pod-lister-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: metallb
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: pod-lister
  namespace: metallb-system
  annotations:
    meta.helm.sh/release-name: 'metallb'
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - list
