# Source: metallb/templates/speaker-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: metallb
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: speaker
  namespace: metallb-system
  annotations:
    meta.helm.sh/release-name: 'metallb'
