# Source: metallb/templates/metallb-system-controller-crb.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: metallb
    gitops.jenkins-x.io/pipeline: 'cluster'
  name: metallb-system:controller
  annotations:
    meta.helm.sh/release-name: 'metallb'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metallb-system:controller
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: metallb-system
